
DROP TABLE RND_DOCUMENT;
DROP TABLE RND_INSTRUCTOR;
DROP TABLE RND_STUDENT;
DROP TABLE RND_ACTOR;
DROP TABLE RND_GROUP_MEMBER;
DROP TABLE RND_GROUP;
DROP TABLE RND_USER;
DROP TABLE RND_PRINCIPAL_ROLE;
DROP TABLE RND_PRINCIPAL;
-- =============================================================================================
-- RND_PRINCIPAL, RND_PRINCIPAL_ROLE
-- =============================================================================================

CREATE
TABLE RND_PRINCIPAL
(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRINCIPAL_TYPE INT(1) NOT NULL,
  LOCKED BIT(1) NOT NULL,
  -- STANDARD METADATA COLUMN
  M_ST INT(1) DEFAULT 0,
  C_ID BIGINT(20) DEFAULT 0,
  C_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  M_ID BIGINT(20),
  M_TS TIMESTAMP,
  D_ID BIGINT(20),
  D_TS TIMESTAMP,
  PRIMARY KEY USING BTREE (ID)
);

CREATE
TABLE RND_PRINCIPAL_ROLE
(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRINCIPAL_ID BIGINT(20) NOT NULL,
  ROLE_TYPE INT(1) NOT NULL,
  -- STANDARD METADATA COLUMN
  M_ST    INT(1) DEFAULT 0,
  C_ID    BIGINT(20) DEFAULT 0,
  C_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  M_ID    BIGINT(20),
  M_TS    TIMESTAMP,
  D_ID    BIGINT(20),
  D_TS    TIMESTAMP,
  PRIMARY KEY USING BTREE (ID)
);
ALTER TABLE RND_PRINCIPAL_ROLE ADD CONSTRAINT FK_RND_PCPL_1 FOREIGN KEY (PRINCIPAL_ID) REFERENCES RND_PRINCIPAL (ID);

-- =============================================================================================
-- RND_USER, RND_GROUP, RND_GROUP_MEMBER
-- =============================================================================================

CREATE
TABLE RND_USER
(
  ID  BIGINT(20) NOT NULL,
  REALNAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  ACTOR_ID BIGINT(20),
  PRIMARY KEY USING BTREE (ID)
);
ALTER TABLE RND_USER ADD CONSTRAINT FK_RND_USER_1 FOREIGN KEY (ID) REFERENCES RND_PRINCIPAL (ID);

CREATE
TABLE RND_GROUP
(
  ID BIGINT(20) NOT NULL,
  PRIMARY KEY USING BTREE (ID)
);

ALTER TABLE RND_GROUP ADD CONSTRAINT FK_RND_GROUP_1 FOREIGN KEY (ID) REFERENCES RND_PRINCIPAL (ID);


CREATE
TABLE RND_GROUP_MEMBER
(
  ID  BIGINT(20) NOT NULL AUTO_INCREMENT,
  GROUP_ID  BIGINT(20) NOT NULL,
  MEMBER_ID  BIGINT(20) NOT NULL,
  -- STANDARD METADATA COLUMN
  M_ST    INT(1) DEFAULT 0,
  C_ID    BIGINT(20) DEFAULT 0,
  C_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  M_ID    BIGINT(20),
  M_TS    TIMESTAMP,
  D_ID    BIGINT(20),
  D_TS    TIMESTAMP,
  PRIMARY KEY USING BTREE (ID)
);
ALTER TABLE RND_GROUP_MEMBER ADD CONSTRAINT FK_RND_GROUP_MEMBER_1 FOREIGN KEY (GROUP_ID) REFERENCES RND_GROUP (ID);
ALTER TABLE RND_GROUP_MEMBER ADD CONSTRAINT FK_RND_GROUP_MEMBER_2 FOREIGN KEY (MEMBER_ID) REFERENCES RND_PRINCIPAL (ID);

-- =============================================================================================
-- RND_ACTOR, RND_STUDENT, RND_INSTRUCTOR
-- =============================================================================================

CREATE
TABLE RND_ACTOR
(
  ID  BIGINT(20) NOT NULL AUTO_INCREMENT,
  ACTOR_TYPE INT(1) NOT NULL,
  IDENTITY_NO VARCHAR(100) NOT NULL,
  NRIC_NO VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS1 VARCHAR(100) NOT NULL,
  ADDRESS2 VARCHAR(100) NOT NULL,
  ADDRESS3 VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PHONE VARCHAR(100) NOT NULL,
  FAX VARCHAR(100) NOT NULL,
  -- STANDARD METADATA COLUMN
  M_ST    INT(1) DEFAULT 0,
  C_ID    BIGINT(20) DEFAULT 0,
  C_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  M_ID    BIGINT(20),
  M_TS    TIMESTAMP,
  D_ID    BIGINT(20),
  D_TS    TIMESTAMP,
  PRIMARY KEY USING BTREE (ID)
);


CREATE
TABLE RND_INSTRUCTOR
(
  ID  BIGINT(20),
  PRIMARY KEY USING BTREE (ID)
);
ALTER TABLE RND_INSTRUCTOR ADD CONSTRAINT FK_RND_INSTRUCTOR_1 FOREIGN KEY (ID) REFERENCES RND_ACTOR (ID);

CREATE
TABLE RND_STUDENT
(
  ID  BIGINT(20),
  PRIMARY KEY USING BTREE (ID)
);
ALTER TABLE RND_STUDENT ADD CONSTRAINT FK_RND_STUDENT_1 FOREIGN KEY (ID) REFERENCES RND_ACTOR (ID);

-- =============================================================================================
-- RND_DOCUMENT
-- =============================================================================================

CREATE
TABLE RND_DOCUMENT
(
  ID  BIGINT(20),
  DOCUMENT_TYPE INT(1) NOT NULL,
  REFERENCE_NO VARCHAR(100) NOT NULL,
  SOURCE_NO VARCHAR(100) NOT NULL,
  -- STANDARD METADATA COLUMN
  M_ST    INT(1) DEFAULT 0,
  C_ID    BIGINT(20) DEFAULT 0,
  C_TS    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  M_ID    BIGINT(20),
  M_TS    TIMESTAMP,
  D_ID    BIGINT(20),
  D_TS    TIMESTAMP,
  -- STANDARD FLOWDATA COLUMN
  FD_ST INT(2) DEFAULT 0,
  DT_ID BIGINT(20),
  RQ_ID BIGINT(20),
  RG_ID BIGINT(20),
  PR_ID BIGINT(20),
  QR_ID BIGINT(20),
  CK_ID BIGINT(20),
  VF_ID BIGINT(20),
  AV_ID BIGINT(20),
  CL_ID BIGINT(20),
  UP_ID BIGINT(20),
  UQ_ID BIGINT(20),
  UV_ID BIGINT(20),
  PT_ID BIGINT(20),
  RM_ID BIGINT(20),
  EV_ID BIGINT(20),
  SL_ID BIGINT(20),
  DT_TS TIMESTAMP,
  RQ_TS TIMESTAMP,
  RG_TS TIMESTAMP,
  PR_TS TIMESTAMP,
  QR_TS TIMESTAMP,
  CK_TS TIMESTAMP,
  VF_TS TIMESTAMP,
  AV_TS TIMESTAMP,
  CL_TS TIMESTAMP,
  UP_TS TIMESTAMP,
  UQ_TS TIMESTAMP,
  UV_TS TIMESTAMP,
  PT_TS TIMESTAMP,
  RM_TS TIMESTAMP,
  EV_TS TIMESTAMP,
  SL_TS TIMESTAMP,
  PRIMARY KEY USING BTREE (ID)
);


